title: youthynf's blog
email: yannengfa@126.com
description: >- # this means to ignore newlines until "baseurl:"
   记录、分享
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://youthynf.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  youthynf

# Build settings
theme: minima
plugins:
  - jekyll-feed